version: '3.7'

services:
    node:
      build:
        context: ./homework_2
        dockerfile: Dockerfile
      container_name: mentoring_node
      volumes:
       - ./homework_2:/usr/src/app
       - /usr/src/app/node_modules
      ports:
        - "5000:5000"
      depends_on:
        - database
    database:
      image: postgres
      container_name: mentoring_postgres
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: mentoring
      volumes:
        - ./homework_2/src/config/init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - "5432:5432"
